version: "3"

services:
    php:
        image: docker-php
        container_name: container-php
        restart: always
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${SITE_DIR}:/www
            - ./runtime/php/php:/usr/local/etc/php:ro
            - ./runtime/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    nginx:
        image: nginx:1.11
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${SITE_DIR}:/www
            - ${NGINX_CONF}/.well-known:/www/.well-known
            - ${NGINX_CONF}/nginx.conf:/etc/nginx/nginx.conf:ro
            - ${NGINX_CONF}/conf.d:/etc/nginx/conf.d:ro
        depends_on:
            - php
        # logging:
        #     driver: 'fluentd'
        #     options:
        #         fluentd-address: '${LOG_IP}:${FLUENTD_PORT}'
        #         tag: 'nginx-development'

    # postgres
    postgres:
        image: postgres:9.6
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=xxoo
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./runtime/postgres/data:/var/lib/postgresql/data

    # 说明:
    # port: 6379
    # conf: /usr/local/etc/redis/redis.conf
    redis:
        image: redis:3.2
        container_name: container-redis
        restart: always
        ports:
            - 6379:6379
        volumes:
            - /etc/localtime:/etc/localtime:ro
