version: "3"

services:
    php:
        image: docker-php
        build:
            context: ./php/
            dockerfile: Dockerfile
        container_name: container-php
        restart: always
        environment:
            - TZ=Asia/Shanghai
            - LC_ALL=C.UTF-8
        volumes:
            - ${SITE_DIR}:/www
        extra_hosts:
            - "git.demo.com:192.168.0.1"

    nginx:
        image: nginx:1.11
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ${SITE_DIR}:/www
            - ./nginx/.well-known:/www/.well-known
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
        depends_on:
            - php

    redis:
        image: redis:4.0-stretch
        container_name: container-redis
        restart: always
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
            - "127.0.0.1:6379:6379"

networks:
    default:
        external:
            name: jetea_net
