version: "3"

services:
    php:
        image: docker-php
        container_name: container-php
        restart: always
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - ${SITE_DIR}:/www
    nginx:
        image: nginx:1.11
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ${SITE_DIR}:/www
            - ./runtime/nginx/.well-known:/www/.well-known
            - ./runtime/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./runtime/nginx/conf.d:/etc/nginx/conf.d:ro
        depends_on:
            - php
        # logging:
        #     driver: 'fluentd'
        #     options:
        #         fluentd-address: '${LOG_IP}:${FLUENTD_PORT}'
        #         tag: 'nginx-development'

    # postgres
    postgres:
        image: postgres:9.6
        restart: always
        ports:
            - 127.0.0.1:5432:5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - ./runtime/postgres/data:/var/lib/postgresql/data

    # mysql
    mysql:
        image: mysql:5.7
        restart: always
        ports:
            - 127.0.0.1:3306:3306
        volumes:
            - ./runtime/mysql/data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - TZ=Asia/Shanghai

    # 说明:
    # port: 6379
    # conf: /usr/local/etc/redis/redis.conf
    redis:
        image: redis:3.2
        container_name: container-redis
        restart: always
        ports:
            - "127.0.0.1:6379:6379"
