version: "3.8"

services:
    node-exporter:
        image: quay.io/prometheus/node-exporter:latest
        container_name: node_exporter
        restart: unless-stopped
        ports:
            - 9100:9100
        environment:
            - TZ=Asia/Shanghai
        network_mode: "host"
        pid: "host"
        command: 
            - "--path.rootfs=/host"
        volumes:
            - /:/host:ro,rslave
