version: "3"

services:
    prometheus:
        image: prom/prometheus:v2.8.0
        restart: always
        ports:
            - 127.0.0.1:9090:9090
        environment:
            - TZ=Asia/Shanghai
        command:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --web.console.libraries=/usr/share/prometheus/console_libraries
            - --web.console.templates=/usr/share/prometheus/consoles
            - --storage.tsdb.retention.time=10d
            - --web.external-url=http://localhost:9090
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml #任务需要配置好
            - ./task.json:/etc/prometheus/task.json
            - ../runtime/prometheus/data:/prometheus
        extra_hosts:
            - log.goblin:192.168.0.1

networks:
    default:
        external:
            name: jetea_net
