global:
  scrape_interval:     1m
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: kod_task
    file_sd_configs:
      - files:
        - task.json

  - job_name: prometheus_shine
    static_configs:
      - targets: ['127.0.0.1:9090']
        labels:
            group: 'prometheus_label'

  - job_name: node_exporter_shine
    static_configs:
      - targets: ['log.goblin:9100']
        labels:
            group: 'node_log_label'
