global:
  scrape_interval:     1m
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: mysql
    static_configs:
      - targets: ['192.168.31.76:9104']

  - job_name: mac
    static_configs:
      - targets: ['192.168.31.76:9100']
