version: '3'
services:
  elasticsearch:
    image: elasticsearch:latest
    restart: always
    environment:
      - cluster.name=medatc-es
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ../runtime/elasticsearch/data:/usr/share/elasticsearch/data
	  # /usr/share/elasticsearch/config 配置
    ports:
      - 9200:9200
	  # 9300
