version: '3'
services:
  es:
    image: es-img
    build:
        context: ./
        dockerfile: Dockerfile
    restart: always
    environment:
      - cluster.name=test-name
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - xpack.ml.enabled=false
    volumes:
      - ../runtime/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

# 9300
# /usr/share/elasticsearch/config 配置

networks:
    default:
        external:
            name: jetea_net
