version: "3"

services:
    beanstalkd:
        image: docker-beanstalkd
        build:
            context: ./
            dockerfile: Dockerfile
        restart: always
        ports:
            - 11300:11300
        volumes:
            - ../runtime/beanstalkd:/var/lib/beanstalkd

networks:
    default:
        external:
            name: jetea_net
