version: "3"

services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        ports:
            - 127.0.0.1:3306:3306
        volumes:
            - ../runtime/mysql/data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - TZ=Asia/Shanghai
            - LC_ALL=C.UTF-8

networks:
    default:
        external:
            name: jetea_net
