version: "3"

services:
    mysql:
        image: mysql:5.7
        restart: always
        ports:
            - 127.0.0.1:3306:3306
        volumes:
            - ../runtime/mysql/data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - TZ=Asia/Shanghai
