version: "3"

services:
    # https://docs.influxdata.com/influxdb/v1.7/administration/config/
    influxdb:
        image: influxdb:1.7
        restart: always
        environment:
            - TZ=Asia/Shanghai
            - INFLUXDB_GRAPHITE_ENABLED=false
            - INFLUXDB_DATA_MAX_SERIES_PER_DATABASE=0
            - INFLUXDB_DATA_MAX_VALUES_PER_TAG=0
            - INFLUXDB_HTTP_MAX_BODY_SIZE=0
            - INFLUXDB_HTTP_AUTH_ENABLED=true
            - INFLUXDB_ADMIN_USER=root
            - INFLUXDB_ADMIN_PASSWORD=123123
        ports:
            - "8086:8086" # HTTP API port
        volumes:
            - ../runtime/influxdb/data:/var/lib/influxdb

networks:
    default:
        external:
            name: jetea_net
