FROM docker-php

RUN sed -i 's#pm = dynamic#pm = static#' /usr/local/etc/php-fpm.d/www.conf \
        && sed -i 's#pm.max_children = 5#pm.max_children = 20#' /usr/local/etc/php-fpm.d/www.conf \
        && sed -i 's#;pm.max_requests = 500#pm.max_requests = 500#' /usr/local/etc/php-fpm.d/www.conf

# 共享目录给nginx
VOLUME /www

WORKDIR /www
